<?php

/***************** DO NOT EDIT THIS FILE *************************
******************************************************************

INFORMATION:
------------

This is a core theme file, you should not need to edit 
this file directly. Code changes maybe lost during updates.

LAST UPDATED: June 26th 2011
EDITED BY: MARK FAIL
------------------------------------------------------------------

******************************************************************/

@header( 'HTTP/1.1 404 Not found', true, 404 );

include("template_".strtolower(PREMIUMPRESS_SYSTEM)."/_404.php");

?>